//
//  Shark.swift
//  Cafe-ios
//
//  Created by Антон Абалуев on 29.11.2025.
// Generated by Shark https://github.com/kaandedeoglu/Shark

import UIKit

// swiftlint:disable all
// swiftformat:disable all
private let bundle: Bundle = {
    class Custom {}
    return Bundle(for: Custom.self)
}()

public enum Shark {
    public enum I: CaseIterable {
        public static var appIcon: UIImage { return UIImage(named:"appIcon", in: bundle, compatibleWith: nil)! }
        public static var logoImage: UIImage { return UIImage(named:"logoImage", in: bundle, compatibleWith: nil)! }
        public static var activeCustomImage: UIImage { return UIImage(named:"activeCustomImage", in: bundle, compatibleWith: nil)! }
        public static var inactiveCustomImage: UIImage { return UIImage(named:"inactiveCustomImage", in: bundle, compatibleWith: nil)! }
        public static var category: UIImage { return UIImage(named:"category", in: bundle, compatibleWith: nil)! }
        public static var profile: UIImage { return UIImage(named:"profile", in: bundle, compatibleWith: nil)! }
        public static var changePasswordButton: UIImage { return UIImage(named:"changePasswordButton", in: bundle, compatibleWith: nil)! }
    }

    public enum C: CaseIterable {
        public static var accentColor: UIColor { return UIColor(named: "AccentColor", in: bundle, compatibleWith: nil)! }
        public static var blueGreyDarken1: UIColor { return UIColor(named: "blueGreyDarken1", in: bundle, compatibleWith: nil)! }
        public static var blueGreyDarken3: UIColor { return UIColor(named: "blueGreyDarken3", in: bundle, compatibleWith: nil)! }
        public static var blueGreyDarken4: UIColor { return UIColor(named: "blueGreyDarken4", in: bundle, compatibleWith: nil)! }
        public static var blueGreyLighten3: UIColor { return UIColor(named: "blueGreyLighten3", in: bundle, compatibleWith: nil)! }
        public static var customError: UIColor { return UIColor(named: "customError", in: bundle, compatibleWith: nil)! }
        public static var greyLighten5: UIColor { return UIColor(named: "greyLighten5", in: bundle, compatibleWith: nil)! }
        public static var lightBlueDarken4: UIColor { return UIColor(named: "lightBlueDarken4", in: bundle, compatibleWith: nil)! }
    }

    public enum S {
        public static var LaunchScreen: UIStoryboard { return UIStoryboard(name: "LaunchScreen", bundle: bundle) }
    }

    public enum D: CaseIterable {
    }
}
