//
//  Shark.swift
//  Cafe-ios
//
//  Created by Шаген  Арабачян on 29.11.2025.
// Generated by Shark https://github.com/kaandedeoglu/Shark

import UIKit

// swiftlint:disable all
// swiftformat:disable all
private let bundle: Bundle = {
    class Custom {}
    return Bundle(for: Custom.self)
}()

public enum Shark {
    public enum I: CaseIterable {
        public static var appIcon: UIImage { return UIImage(named:"appIcon", in: bundle, compatibleWith: nil)! }
        public static var antonImageCafe: UIImage { return UIImage(named:"antonImageCafe", in: bundle, compatibleWith: nil)! }
    }

    public enum C: CaseIterable {
        public static var accentColor: UIColor { return UIColor(named: "AccentColor", in: bundle, compatibleWith: nil)! }
        public static var blueGreyDarken1: UIColor { return UIColor(named: "blueGreyDarken1", in: bundle, compatibleWith: nil)! }
        public static var blueGreyDarken3: UIColor { return UIColor(named: "blueGreyDarken3", in: bundle, compatibleWith: nil)! }
    }

    public enum S {
        public static var LaunchScreen: UIStoryboard { return UIStoryboard(name: "LaunchScreen", bundle: bundle) }
    }

    public enum D: CaseIterable {
    }
}
